### ISSUE TITLE
Warning with the powered_by_google_inverse image

### ISSUE THREAD

**Issue by andreperegrina** [hibiken/react-places-autocomplete#129]
When i use the react-places-autocomplete plugin with Webpack it appears this error:

```
WARNING in ./~/react-places-autocomplete/dist/images/powered_by_google_inverse.png
Module parse failed: /USERDIRECTORY/PROJECT_NAME/node_modules/react-places-autocomplete/dist/images/powered_by_google_inverse.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/USERDIRECTORY/PROJECT_NAME/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/USERDIRECTORY/PROJECT_NAME/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/USERDIRECTORY/PROJECT_NAME/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/USERDIRECTORY/PROJECT_NAME/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /USERDIRECTORY/PROJECT_NAME/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/USERDIRECTORY/PROJECT_NAME/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /USERDIRECTORY/PROJECT_NAME/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/react-places-autocomplete/dist/images ^\.\/powered_by_google_.*\.png$

WARNING in ./~/react-places-autocomplete/dist/images/powered_by_google_default.png
Module parse failed: /USERDIRECTORY/PROJECT_NAME/node_modules/react-places-autocomplete/dist/images/powered_by_google_default.png Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/USERDIRECTORY/PROJECT_NAME/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/USERDIRECTORY/PROJECT_NAME/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/USERDIRECTORY/PROJECT_NAME/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/USERDIRECTORY/PROJECT_NAME/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/USERDIRECTORY/PROJECT_NAME/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /USERDIRECTORY/PROJECT_NAME/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/USERDIRECTORY/PROJECT_NAME/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /USERDIRECTORY/PROJECT_NAME/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/react-places-autocomplete/dist/images ^\.\/powered_by_google_.*\.png$

```

**Comment by cp731** [comment]
Add this to webpack:
 {test: /\.(png|jpg)$/, loader: 'url-loader?limit=8192' }
and npm install url-loader
fixed it for me.

**Comment by andreperegrina** [comment]
¡Thanks! @cp731 it solved my problem

**Comment by jonathanphz** [comment]
I'm getting this error but not using webpack - is there an alternative for babel?

**Comment by abhijeet5** [comment]
Adding this to webpack didn't resolve the issue..
{test: /.(png|jpg)$/, loader: 'url-loader?limit=8192' }
